export const SAMPLE_JOBS = [
  {
    id: 1,
    title: 'Software Engineer',
    company: 'TechCorp',
    location: 'San Francisco, CA',
    category: 'Engineering',
    experienceLevel: 'Mid-Level',
    description:
      'As a Software Engineer at TechCorp, you will design, develop, and maintain scalable software solutions that power our global platform. You will collaborate with cross-functional teams to deliver high-quality code, optimize system performance, and ensure seamless integration with third-party services. This role requires strong problem-solving skills and expertise in modern programming languages and frameworks.',
    salaryRange: '$90,000 - $120,000',
    jobType: 'Contract',
    postedDate: '2023-10-01',
    applicationDeadline: '2023-10-31',
    skillsRequired: ['JavaScript', 'Python', 'React', 'Node.js', 'AWS'],
  },
  {
    id: 2,
    title: 'Marketing Manager',
    company: 'AdvertiseNow',
    location: 'New York, NY',
    category: 'Marketing',
    experienceLevel: 'Senior',
    description:
      'As a Marketing Manager at AdvertiseNow, you will lead innovative marketing campaigns to drive brand awareness and growth. You will develop strategies for digital and traditional channels, analyze campaign performance, and mentor a team of marketing professionals. This role requires a creative mindset, strong leadership skills, and a deep understanding of market trends.',
    salaryRange: '$100,000 - $130,000',
    jobType: 'Internship',
    postedDate: '2023-10-02',
    applicationDeadline: '2023-11-15',
    skillsRequired: [
      'Digital Marketing',
      'SEO',
      'Content Strategy',
      'Analytics',
      'Team Leadership',
    ],
  },
  {
    id: 3,
    title: 'Data Analyst',
    company: 'DataWorks',
    location: 'Chicago, IL',
    category: 'Data Science',
    experienceLevel: 'Entry-Level',
    description:
      'As a Data Analyst at DataWorks, you will analyze large datasets to uncover trends and provide actionable insights. You will work closely with stakeholders to understand business needs, create visualizations, and present findings in a clear and concise manner. This role is perfect for someone passionate about data and eager to grow their analytical skills.',
    salaryRange: '$60,000 - $80,000',
    jobType: 'Part-Time',
    postedDate: '2023-10-03',
    applicationDeadline: '2023-11-10',
    skillsRequired: ['SQL', 'Excel', 'Tableau', 'Python', 'Data Visualization'],
  },
  {
    id: 4,
    title: 'Product Manager',
    company: 'InnovateInc',
    location: 'Austin, TX',
    category: 'Product Management',
    experienceLevel: 'Mid-Level',
    description:
      'As a Product Manager at InnovateInc, you will oversee the entire product lifecycle, from ideation to launch. You will collaborate with engineering, design, and marketing teams to deliver high-quality products that meet customer needs. This role requires strong communication skills, a strategic mindset, and a passion for innovation.',
    salaryRange: '$95,000 - $125,000',
    jobType: 'Full-Time',
    postedDate: '2023-10-04',
    applicationDeadline: '2023-11-20',
    skillsRequired: [
      'Product Roadmapping',
      'Agile Methodologies',
      'Stakeholder Management',
      'UX/UI Knowledge',
      'Market Research',
    ],
  },
  {
    id: 5,
    title: 'Graphic Designer',
    company: 'CreativeStudio',
    location: 'Los Angeles, CA',
    category: 'Design',
    experienceLevel: 'Entry-Level',
    description:
      'As a Graphic Designer at CreativeStudio, you will create visually appealing designs for digital and print media. You will work closely with the marketing team to develop branding materials, social media graphics, and website assets. This role is ideal for a creative individual with a strong eye for detail and a passion for design.',
    salaryRange: '$50,000 - $70,000',
    jobType: 'Part-Time',
    postedDate: '2023-10-05',
    applicationDeadline: '2023-11-05',
    skillsRequired: [
      'Adobe Creative Suite',
      'Illustrator',
      'Photoshop',
      'Typography',
      'Branding',
    ],
  },
  {
    id: 6,
    title: 'DevOps Engineer',
    company: 'Cloudify',
    location: 'Seattle, WA',
    category: 'Engineering',
    experienceLevel: 'Senior',
    description:
      'As a DevOps Engineer at Cloudify, you will implement and manage CI/CD pipelines and cloud infrastructure for scalable applications. You will work closely with development and operations teams to ensure seamless deployment and monitoring of systems. This role requires expertise in cloud platforms, automation tools, and a strong understanding of system architecture.',
    salaryRange: '$110,000 - $140,000',
    jobType: 'Full-Time',
    postedDate: '2023-10-06',
    applicationDeadline: '2023-11-25',
    skillsRequired: ['Docker', 'Kubernetes', 'AWS', 'Jenkins', 'Terraform'],
  },
  {
    id: 7,
    title: 'Sales Representative',
    company: 'SellIt',
    location: 'Boston, MA',
    category: 'Sales',
    experienceLevel: 'Entry-Level',
    description:
      'As a Sales Representative at SellIt, you will build relationships with clients and drive sales growth through effective communication. You will identify new business opportunities, negotiate contracts, and provide exceptional customer service. This role is perfect for someone with strong interpersonal skills and a passion for sales.',
    salaryRange: '$45,000 - $65,000',
    jobType: 'Contract',
    postedDate: '2023-10-07',
    applicationDeadline: '2023-11-12',
    skillsRequired: [
      'Sales Techniques',
      'CRM Software',
      'Negotiation',
      'Communication',
      'Customer Relationship Management',
    ],
  },
  {
    id: 8,
    title: 'HR Coordinator',
    company: 'PeopleFirst',
    location: 'Denver, CO',
    category: 'Human Resources',
    experienceLevel: 'Mid-Level',
    description:
      'As an HR Coordinator at PeopleFirst, you will support HR operations, including recruitment, onboarding, and employee engagement. You will ensure compliance with company policies and assist in organizing training programs. This role requires strong organizational skills and a passion for supporting employee growth.',
    salaryRange: '$55,000 - $75,000',
    jobType: 'Internship',
    postedDate: '2023-10-08',
    applicationDeadline: '2023-11-18',
    skillsRequired: [
      'Recruitment',
      'HR Software',
      'Employee Relations',
      'Onboarding',
      'Compliance',
    ],
  },
  {
    id: 9,
    title: 'Financial Analyst',
    company: 'MoneyMatters',
    location: 'San Francisco, CA',
    category: 'Finance',
    experienceLevel: 'Mid-Level',
    description:
      'As a Financial Analyst at MoneyMatters, you will analyze financial data and prepare reports to guide business strategy. You will work closely with stakeholders to identify trends, forecast budgets, and recommend cost-saving measures. This role requires strong analytical skills and attention to detail.',
    salaryRange: '$85,000 - $110,000',
    jobType: 'Part-Time',
    postedDate: '2023-10-09',
    applicationDeadline: '2023-11-22',
    skillsRequired: [
      'Financial Modeling',
      'Excel',
      'Data Analysis',
      'Forecasting',
      'Budgeting',
    ],
  },
  {
    id: 10,
    title: 'Frontend Developer',
    company: 'WebWorks',
    location: 'New York, NY',
    category: 'Engineering',
    experienceLevel: 'Entry-Level',
    description:
      'As a Frontend Developer at WebWorks, you will build responsive and user-friendly web interfaces using modern frameworks. You will collaborate with designers and backend developers to create seamless user experiences. This role is ideal for someone passionate about web development and user-centric design.',
    salaryRange: '$70,000 - $90,000',
    jobType: 'Full-Time',
    postedDate: '2023-10-10',
    applicationDeadline: '2023-11-30',
    skillsRequired: ['HTML', 'CSS', 'JavaScript', 'React', 'Responsive Design'],
  },
  {
    id: 11,
    title: 'Content Writer',
    company: 'WriteAway',
    location: 'Chicago, IL',
    category: 'Content Creation',
    experienceLevel: 'Entry-Level',
    description:
      'As a Content Writer at WriteAway, you will create engaging and SEO-friendly content for blogs, websites, and social media. You will work closely with the marketing team to develop content strategies and ensure brand consistency. This role is perfect for someone with a passion for writing and storytelling.',
    salaryRange: '$40,000 - $60,000',
    jobType: 'Full-Time',
    postedDate: '2023-10-11',
    applicationDeadline: '2023-11-14',
    skillsRequired: [
      'SEO',
      'Content Writing',
      'Copywriting',
      'Editing',
      'Social Media',
    ],
  },
  {
    id: 12,
    title: 'UX Designer',
    company: 'DesignHub',
    location: 'Austin, TX',
    category: 'Design',
    experienceLevel: 'Mid-Level',
    description:
      'As a UX Designer at DesignHub, you will design intuitive user experiences and interfaces for web and mobile applications. You will conduct user research, create wireframes, and collaborate with developers to bring designs to life. This role requires a strong understanding of user-centered design principles.',
    salaryRange: '$80,000 - $100,000',
    jobType: 'Full-Time',
    postedDate: '2023-10-12',
    applicationDeadline: '2023-11-28',
    skillsRequired: [
      'Figma',
      'Sketch',
      'Wireframing',
      'Prototyping',
      'User Research',
    ],
  },
  {
    id: 13,
    title: 'Business Analyst',
    company: 'StrategyPlus',
    location: 'Seattle, WA',
    category: 'Business',
    experienceLevel: 'Senior',
    description:
      'As a Business Analyst at StrategyPlus, you will analyze business processes and recommend improvements to drive efficiency. You will work closely with stakeholders to gather requirements, create reports, and implement solutions. This role requires strong analytical and problem-solving skills.',
    salaryRange: '$95,000 - $120,000',
    jobType: 'Full-Time',
    postedDate: '2023-10-13',
    applicationDeadline: '2023-11-25',
    skillsRequired: [
      'Business Analysis',
      'Process Improvement',
      'Data Analysis',
      'Stakeholder Management',
      'Project Management',
    ],
  },
  {
    id: 14,
    title: 'Customer Support Specialist',
    company: 'HelpDesk',
    location: 'Los Angeles, CA',
    category: 'Customer Service',
    experienceLevel: 'Entry-Level',
    description:
      'As a Customer Support Specialist at HelpDesk, you will provide exceptional customer support and resolve issues in a timely manner. You will assist customers via phone, email, and chat, ensuring a positive experience. This role is ideal for someone with strong communication skills and a customer-first mindset.',
    salaryRange: '$35,000 - $50,000',
    jobType: 'Full-Time',
    postedDate: '2023-10-14',
    applicationDeadline: '2023-11-20',
    skillsRequired: [
      'Customer Service',
      'Problem Solving',
      'Communication',
      'CRM Software',
      'Patience',
    ],
  },
  {
    id: 15,
    title: 'Network Administrator',
    company: 'NetSolutions',
    location: 'Boston, MA',
    category: 'IT',
    experienceLevel: 'Mid-Level',
    description:
      'As a Network Administrator at NetSolutions, you will manage and maintain network infrastructure to ensure optimal performance. You will troubleshoot issues, implement security measures, and support internal teams. This role requires strong technical skills and attention to detail.',
    salaryRange: '$75,000 - $95,000',
    jobType: 'Full-Time',
    postedDate: '2023-10-15',
    applicationDeadline: '2023-11-30',
    skillsRequired: [
      'Network Security',
      'Cisco',
      'Firewalls',
      'Troubleshooting',
      'LAN/WAN',
    ],
  },
];
